# src/bdf/__init__.py
from __future__ import annotations

from pathlib import Path
from typing import Any
import warnings

# ---- version ----
try:
    from ._version import __version__  # generated by build tooling if present
except Exception:  # pragma: no cover
    try:
        # Ask the installed distribution for a version; guess dist name from module
        from importlib.metadata import version as _pkg_version  # type: ignore
        _dist_name = __name__.split(".", 1)[0]
        __version__ = _pkg_version(_dist_name)
    except Exception:
        __version__ = "0+unknown"

# ---- public facades ----
def detect_cycler(path: Any):
    """
    Detect which cycler plugin should parse the file at 'path'.
    Accepts str/Path/PathLike; returns a detection result object.
    """
    from .detect import detect
    return detect(path)

def read_raw_to_bdf(path: Any, as_: str | None = None, *, validate: bool = True):
    """
    Auto-detect (or force via as_) → parse vendor file → normalize to BDF DataFrame.
    If validate=True, run BDF validation (raises on failure).
    """
    from .detect import load_plugin
    from .normalize import to_bdf
    from .validate import validate_df

    plugin = load_plugin(path, as_=as_)
    df_vendor = plugin.parse(path)
    df_bdf = to_bdf(df_vendor, plugin_id=plugin.id)
    if validate:
        validate_df(df_bdf, strict=True)
    return df_bdf

def validate_bdf(path_or_df: Any, *, strict: bool = False):
    """
    Validate a BDF DataFrame or a path to a BDF CSV/Parquet.
    Returns a ValidationReport (or raises if strict=True and errors are found).
    """
    from .validate import validate_df, validate_path
    import os
    try:
        import pandas as pd  # optional
    except Exception:  # pragma: no cover
        pd = None  # type: ignore

    if isinstance(path_or_df, (str, bytes, os.PathLike, Path)):
        return validate_path(path_or_df, strict=strict)
    if pd is not None and isinstance(path_or_df, pd.DataFrame):
        return validate_df(path_or_df, strict=strict)
    raise TypeError("validate_bdf expects a path (str/Path) or a pandas DataFrame.")

# define __all__ before extending
__all__ = ["detect_cycler", "read_raw_to_bdf", "validate_bdf", "__version__"]

def _warn_optional(feature: str, exc: Exception) -> None:
    warnings.warn(
        f"Optional '{feature}' features are unavailable: {exc.__class__.__name__}: {exc}",
        RuntimeWarning,
        stacklevel=2,
    )

# ---- optional re-exports (data fetching; requires requests/platformdirs) ----
try:
    from .datafetch import (
        load_registry,
        list_registry_entries,
        get_entry,
        fetch_url,
        load_bdf_from_entry,
    )
except Exception as _e:  # pragma: no cover
    # Keep core usable even if extras aren't installed
    _warn_optional("datafetch", _e)
else:
    __all__.extend(
        ["load_registry", "list_registry_entries", "get_entry", "fetch_url", "load_bdf_from_entry"]
    )

# ---- expose cleaning API ----
from .clean import clean_bdf, CleanReport
__all__.extend(["clean_bdf", "CleanReport"])


# ---- expose metadata helpers (JSON-LD/Zenodo) ----
try:
    from .metadata import (
        BDFMetadata,
        Creator,
        RelatedIdentifier,
        save_jsonld,
        BDF_CSVW_SCHEMA_URL,
    )
except Exception as _e:  # pragma: no cover
    _warn_optional("metadata", _e)
else:
    __all__.extend(
        ["BDFMetadata", "Creator", "RelatedIdentifier", "save_jsonld", "BDF_CSVW_SCHEMA_URL"]
    )

# ---- optional: re-export common plotting helpers for convenience ----
try:
    from .visualize import line_plot, plot_voltage_current
except Exception:
    # plotting is entirely optional; no warning needed
    pass
else:
    __all__.extend(["line_plot", "plot_voltage_current"])
