# src/bdf/__init__.py
from __future__ import annotations
from pathlib import Path
from typing import Optional, Union

# ---------------------------
# Version
# ---------------------------
try:
    from ._version import __version__  # generated by your build
except Exception:  # pragma: no cover
    __version__ = "0+unknown"

# ---------------------------
# Public facades
# ---------------------------

def detect_cycler(path: Union[str, Path]):
    """
    Detect which cycler plugin should parse the file at 'path'.
    Returns a SniffResult.
    """
    from .detect import detect
    return detect(path)

def read_raw_to_bdf(
    path: Union[str, Path],
    as_: Optional[str] = None,
    *,
    validate: bool = True,
):
    """
    Auto-detect (or force via as_) → parse vendor file → normalize to BDF DataFrame.
    If validate=True, runs strict BDF validation (raises on error).
    """
    from .detect import load_plugin
    from .normalize import to_bdf
    from .validate import validate_df  # raises BDFValidationError on strict failure

    p = Path(path)
    plugin = load_plugin(p, as_=as_)
    df_vendor = plugin.parse(p)
    df_bdf = to_bdf(df_vendor, plugin_id=plugin.id)

    if validate:
        validate_df(df_bdf, strict=True)

    return df_bdf

def validate_bdf(path_or_df, *, strict: bool = False):
    """
    Validate a BDF DataFrame or a path to a file containing BDF data.
    Returns ValidationReport; if strict=True, raises BDFValidationError on failure.
    """
    from pathlib import Path as _Path
    from .validate import validate_df, validate_path
    if isinstance(path_or_df, (str, _Path)):
        return validate_path(path_or_df, strict=strict)
    return validate_df(path_or_df, strict=strict)

# ---------------------------
# Re-exports (convenience API)
# ---------------------------
from .validate import ValidationReport, BDFValidationError
from .io import load as load_bdf, save_csv, save_parquet
from .visualize import plot
from .clean import clean_bdf, CleanReport
from .datafetch import (
    load_registry,
    list_registry_entries,
    get_entry,
    fetch_url,
    load_bdf_from_entry,
)
from .metadata import (
    BDFMetadata,
    Creator,
    RelatedIdentifier,
    save_jsonld,
)

__all__ = [
    "__version__",
    # facades
    "detect_cycler",
    "read_raw_to_bdf",
    "validate_bdf",
    # validation types
    "ValidationReport",
    "BDFValidationError",
    # IO
    "load_bdf",
    "save_csv",
    "save_parquet",
    # visualization
    "plot",
    # cleaning
    "clean_bdf",
    "CleanReport",
    # dataset registry / fetching
    "load_registry",
    "list_registry_entries",
    "get_entry",
    "fetch_url",
    "load_bdf_from_entry",
    # metadata
    "BDFMetadata",
    "Creator",
    "RelatedIdentifier",
    "save_jsonld",
]
